# learning about numpy

In [4]:
import numpy as np
import time

## creating array from list

In [3]:
array_1d = np.array([1,2,3,4])
print("1D array: ", array_1d)
array_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", array_2d)

1D array:  [1 2 3 4]
2D array:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [6]:
py_list = [1,2,3,4]
print("Python list multiplication: ", py_list * 2)
np_array= np.array([1,2,3,4]) #element wise multiplication
print("numpy array multiplication: ", np_array * 2)


start1 = time.time()
py_list2 = [i*2 for i in range(10000000)]
print("\n List operation time: ", time.time()-start1)
start2 = time.time()
np_array2= np.arange(10000000) * 2
print("\n List operation time: ", time.time()-start2)


Python list multiplication:  [1, 2, 3, 4, 1, 2, 3, 4]
numpy array multiplication:  [2 4 6 8]

 List operation time:  0.6784713268280029

 List operation time:  0.040547847747802734


### creating array from scratch

In [8]:
zeros= np.zeros((3,3))
print("zeros array: \n", zeros)
ones= np.ones((3,3))
print("ones array: \n", ones)
full= np.full((3,3), 69)
print("full array: \n", full)
random= np.random.random((3,3))
print("random array: \n",random)
sequence= np.arange(0,11, 2)
print("sequence array: \n",sequence)

zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[69 69 69]
 [69 69 69]
 [69 69 69]]
random array: 
 [[0.81136979 0.57057778 0.3822463 ]
 [0.93731616 0.25774896 0.88143965]
 [0.55433743 0.94843206 0.67242649]]
sequence array: 
 [ 0  2  4  6  8 10]


### Matrice, Vector and Tensor

In [13]:
vector= np.array([1,2,3])
print("vector: \n", vector)
matrix= np.array([[1,2,3],
                   [4,5,6]])
print("matrix: \n", matrix)
tensor= np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print("tensor: \n", tensor)

vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array props

In [14]:
arr= np.array([[1,2,3],
               [4,5,6]])

print("shape: ", arr.shape)
print("dimension: ", arr.ndim)
print("size: ", arr.size)
print("data types: ", arr.dtype)

shape:  (2, 3)
dimension:  2
size:  6
data types:  int64


###Array reshaping

In [21]:
arr = np.arange(9)
print("original array: ", arr)
reshaped= arr.reshape((3,3))
print("\n reshaped array: \n", reshaped)
flatten= reshaped.flatten()
print("\n flatten array: ", flatten)
raveled= reshaped.ravel() #it returns view insted of copy, so original is safe
print("\n raveled array: ", raveled)

transpose = reshaped.T
print("\n transopose array: ", transpose)

original array:  [0 1 2 3 4 5 6 7 8]

 reshaped array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 flatten array:  [0 1 2 3 4 5 6 7 8]

 raveled array:  [0 1 2 3 4 5 6 7 8]

 transopose array:  [[0 3 6]
 [1 4 7]
 [2 5 8]]
