#Numpy array operations

In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
print("basic slicing: ", arr[2:7])
print("with step slicing: ", arr[1:8:2])
print("negative slicing: ", arr[-3])

basic slicing:  [2 3 4 5 6]
with step slicing:  [1 3 5 7]
negative slicing:  7


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element: ", arr_2d[1,2])
print("Entire row: ", arr_2d[0])
print("Entire column: ", arr_2d[:, 1])


Specific element:  6
Entire row:  [1 2 3]
Entire column:  [2 5 8]


#Sorting

In [5]:
unsorted = np.array([1,45,3,6,7,2,8,2,69])
print("Sorted array: ", np.sort(unsorted))
unsorted_2d_arr = np.array([[3,2],[4,5],[1,6],[9,8]])
print("Sorted array by column: ", np.sort(unsorted_2d_arr, axis=0))
print("Sorted array by row: ", np.sort(unsorted_2d_arr, axis=1))

Sorted array:  [ 1  2  2  3  6  7  8 45 69]
Sorted array by column:  [[1 2]
 [3 5]
 [4 6]
 [9 8]]
Sorted array by row:  [[2 3]
 [4 5]
 [1 6]
 [8 9]]


##Filter

In [6]:
numbers= np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers= numbers[numbers %2 == 0]
print("Even numbers: ", even_numbers)

Even numbers:  [ 2  4  6  8 10]


##Filter by mask

In [7]:
mask= numbers>5
print("Numbers greater than 5 in ",numbers," this array is: ", numbers[mask])

Numbers greater than 5 in  [ 1  2  3  4  5  6  7  8  9 10]  this array is:  [ 6  7  8  9 10]


##Fancy indedexing vvs np.where()

In [8]:
indices= [0,2,4,8]
print(numbers[indices])

wheer_result= np.where(numbers>5)
print("NP where: ", numbers[wheer_result])

[1 3 5 9]
NP where:  [ 6  7  8  9 10]


In [10]:
conditional_array  = np.where(numbers>5, numbers*4, numbers) # numbers>5 is condition if it is true it will do numbers*4 or else it will return the numbers
print("conditional arrays: ", conditional_array)

conditional arrays:  [ 1  2  3  4  5 24 28 32 36 40]


###Adding and Removing data

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1, arr2))
# combined = arr1+arr2 will add both the array:- this will be the result [5,7,9]
print(combined)

[1 2 3 4 5 6]


###array compatibility

In [14]:
a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.array([7,8,9,0])

print("compatibility shape of a and b: ", a.shape == b.shape)
print("compatibility shape of a and c: ", a.shape == c.shape)

compatibility shape of a and b:  True
compatibility shape of a and c:  False


In [16]:
original= np.array([[1,2],[3,4]])
new_row= np.array([[5,6]])
with_new_row = np.vstack((original, new_row))

print("og array with new row: ", with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print("og array with new col: ", with_new_col)


og array with new row:  [[1 2]
 [3 4]
 [5 6]]
og array with new col:  [[1 2 7]
 [3 4 8]]


In [17]:
arr = np.array([1,2,3,4,5,6])
deleted = np.delete(arr, 2)

print("array after delettion: ", deleted)

array after delettion:  [1 2 4 5 6]
